
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: event-tracker-cluster-role
rules:
- apiGroups:
  - eventtracker.litmuschaos.io
  resources:
  - eventtrackerpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventtracker.litmuschaos.io
  resources:
  - eventtrackerpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - ""
    - extensions
    - apps
  resources:
    - deployments
    - daemonsets
    - statefulsets
    - pods
    - configmaps
  verbs:
    - get
    - list
    - watch