---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: #{AGENT-NAMESPACE}
data:
  SERVER_ADDR: #{SERVER_ADDR}
  CLUSTER_ID: #{CLUSTER_ID}
  ACCESS_KEY: #{ACCESS_KEY}
  AGENT_SCOPE: #{AGENT-SCOPE}
  IS_CLUSTER_CONFIRMED: "false"
  COMPONENTS: |
    DEPLOYMENTS: ["app=chaos-exporter", "name=chaos-operator", "app=event-tracker", "app=workflow-controller"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: #{AGENT-NAMESPACE}
  labels:
    app: subscriber
spec:
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      serviceAccountName: #{SUBSCRIBER-SERVICE-ACCOUNT}
      containers:
        - name: subscriber
          image: #{SUBSCRIBER-IMAGE}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: agent-config
          env:
            - name: AGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-tracker
  name: event-tracker
  namespace: #{AGENT-NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-tracker
  template:
    metadata:
      labels:
        app: event-tracker
    spec:
      serviceAccountName: event-tracker-sa
      containers:
        - image: #{EVENT-TRACKER-IMAGE}
          imagePullPolicy: Always
          name: litmus-event-tracker
          envFrom:
            - configMapRef:
                name: agent-config
          env:
            - name: AGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace