---
apiVersion: v1
kind: Service
metadata:
  name: workflow-controller-metrics
  namespace: #{AGENT-NAMESPACE}
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: workflow-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-controller
  namespace: #{AGENT-NAMESPACE}
spec:
  selector:
    matchLabels:
      app: workflow-controller
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
        - args:
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            -  #{ARGO-WORKFLOW-EXECUTOR}
            - --namespaced
            - --container-runtime-executor
            -  #{ARGO-CONTAINER-RUNTIME-EXECUTOR}
          command:
            - workflow-controller
          image: #{ARGO-WORKFLOW-CONTROLLER}
          name: workflow-controller
          resources:
            limits:
              cpu: 150m
              memory: 250Mi
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: argo
